cabal-version:      3.4
name:               revdep-scanner
version:            0.1.0.0
synopsis:           Scan Gentoo repositories for reverse dependencies

tested-with:        GHC == { 9.2.8, 9.4.8, 9.6.6, 9.8.4, 9.10.1, 9.12.1 }
-- description:
homepage:           https://github.com/gentoo-haskell/revdep-scanner
license:            AGPL-3.0-only
license-file:       LICENSE
author:             Gentoo Authors
maintainer:         hololeap@protonmail.com
copyright:          Copyright (C) 2025 Gentoo Authors
category:           Development
build-type:         Simple
extra-doc-files:
    CHANGELOG.md
    README.md
-- extra-source-files:

source-repository head
    type:           git
    location:       https://github.com/gentoo-haskell/revdep-scanner.git
    branch:         main

flag pedantic
    description: Enable -Werror
    default:     False
    manual:      True

common warnings
    ghc-options: -Wall
    if flag(pedantic)
        ghc-options:    -Werror

common exe
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

library revdep-scanner-internal
    import:           warnings
    exposed-modules:
        , RevdepScanner.CmdLine
        , RevdepScanner.Display
        , RevdepScanner.Logic
        , RevdepScanner.Types
        , RevdepScanner.Types.ConstraintMap
        , RevdepScanner.Types.DepSet
        , RevdepScanner.Types.ResultMap
        , RevdepScanner.Util
    build-depends:
        , base >=4.16 && <4.22
        , parsable >=0.1 && <0.3
        , portage-hs >=0.1 && <0.3
        , gentoo-utils ^>=0.1
        , bytestring >=0.11.4.0 && <0.13
        , containers >=0.6.7 && <0.8
        , hashable ^>=1.4.7.0
        , list-t ^>= 1.0.5.7
        , mtl ^>=2.3.1
        , nonempty-containers ^>=0.3.4.4
        , prettyprinter ^>=1.7.1
        , prettyprinter-ansi-terminal ^>=1.1.3
        , unordered-containers ^>=0.2
        , text >=1.2.5.0 && <2.2
        , transformers >=0.5.6.2 && <0.7
    hs-source-dirs:   src

    default-language: GHC2021

executable revdep-scanner
    import:           warnings
    main-is:          Main.hs
    -- other-extensions:
    build-depends:
        , revdep-scanner:revdep-scanner-internal
        , base >=4.16 && <4.22
        , portage-hs >=0.1 && <0.3
        , gentoo-utils ^>=0.1
        , conduit ^>=1.3.0
        , list-t ^>= 1.0.5.7
        , mtl ^>=2.3.1
        , pretty-simple ^>=4.1.1.0
        , prettyprinter ^>=1.7.1
        , prettyprinter-ansi-terminal ^>=1.1.3
        , unordered-containers ^>=0.2
    hs-source-dirs:   src-exe
    default-language: GHC2021
